version: '3.8'
services:
  openwa-api:
    image: ghcr.io/rmyndharis/openwa:latest
    restart: unless-stopped
    ports:
      - "2785:2785"
    environment:
      - WA_API_KEY=owa_k1_b9e9c693136c64f58acc4b4bef545788a84867236c513ad84c9630be0f4e3c99
      - ENGINE_TYPE=whatsapp-web.js
      - STORAGE_TYPE=local
      - DATABASE_TYPE=sqlite
    volumes:
      - openwa-data:/app/data

volumes:
  openwa-data:
