version: '3.8'
services:
  openwa-api:
    image: ghcr.io/rmyndharis/openwa:latest
    restart: unless-stopped
    ports:
      - "2785:2785"
    environment:
      - API_KEY=owa_k1_72b538fae9ce803051d7dd3a663ec95928ef9d0d371c0e27d1c7f4add718d8ab
      - ENGINE_TYPE=whatsapp-web.js
      - STORAGE_TYPE=local
      - DATABASE_TYPE=sqlite
    volumes:
      - openwa-data:/app/data

volumes:
  openwa-data:
